language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
before_script:
    - sudo apt-get install pandoc
    - cd ..
    - git clone --depth=50 git://github.com/ovgu-ttz/pyandoc.git
    - ln -s pyandoc/pandoc intervaltree/pandoc
script:
    - python setup.py develop test
